config/routes.rb
Rails.application.routes.draw do


  namespace :users do
    get 'index'  => 'users#index'
  end

  namespace :users do
    get 'money/index'
    post 'money/index' => 'money#update'
    post 'users' => 'registration#create'
    get 'ticket/show'
    get 'ticket/wantdelete/:id' => "ticket#wantdelete", :as => :ticket_wantdelete
    get 'showTickets/:id' => "ticket#showTickets", :as => :ticket_showTickets
    
  end

  get 'events/edit'
  patch 'events/:id' => 'events#update', :as => :events_update

  resources :events, :only => [:index, :new, :create, :show, :edit]

  resources :users, :only => [:index]

  resources :tickets
  
  devise_for :users , :controllers => { registrations: 'users/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  post '/users' => 'users#create'

  


  root :to  => "events#index"
  # root :to  => "tickets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/event.rb
class Event < ApplicationRecord

    has_many :tickets
    has_attached_file :photo
    validates_attachment :photo,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
    validates :artist, :presence => true
    validates :description, :presence => true
    validates :placesNumber, :presence => true
    validates :price_low, :presence => true, numericality: { greater_than: 0, less_than_or_equal_to: :price_high }
    validates :price_high, :presence => true, numericality: { greater_than: 0 }

    validate :event_date_not_from_past
       
    def event_date_not_from_past
        if  event_date.present?
            if  event_date < Date.today
                errors.add(:event_date, 'can\'t be from past.')
            end
        else
            errors.add(:event_date, 'can\'t be blank.')
        end
    end


    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create,:edit] # sprawdzenie czy curent user jest zalogowany a potem czy jest adminem jak nie jest to redirect

  def index
    @events = Event.where("event_date >= :currentDate", {currentDate: Date.today} ).order(:event_date) #order by date
    @eventsOld = Event.where("event_date < :currentDate", {currentDate: Date.today} ).order(event_date: :desc) 
  end

  def new
      @event = Event.new
  end

  def create
    @myErrors=Array.new
    @ifError = false

    event_parmas = params.require(:event).permit(:artist, :placesNumber, :description, :price_low, :price_high, :forAdult, :photo, :event_date, :limitTicket)
    event_parmas[:placesNumberAll] = event_parmas[:placesNumber]
    @event = Event.new(event_parmas)
    puts   @event.inspect
    if event_parmas[:limitTicket].to_i > event_parmas[:placesNumber].to_i
      @myErrors.push([" ",'Invalid number of limit ticket'])
      @ifError = true
    end

    respond_to do |format|
      if @event.valid? && @ifError == false
        @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        for myError in @myErrors
          @event.errors.add( myError[0], myError[1])
        end
         # puts   @event.errors.messages.inspect
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def show
    @event = Event.find(params[:id])
    
    #zarezerwowane bilety
    @ticketsReserved = Ticket.where(event_id: params[:id])
    @ticketReservedArray = Array.new
    for x in @ticketsReserved
      @ticketReservedArray.push(x.seat_id_seq)
    end

    #sprawdzenie czy juz mozna kupowac (mozna kupwoac 1 miesiac przed eventem)
    @canBuy = false
    if @event.event_date - 1.months < Date.today
      @canBuy = true
    end

    #zwiekszenie ceny jezeli jest grane w dniu dzisiejszym 
    if @event.event_date == Date.today && @event.price_high!=@event.price_low #rozwiazanie tymczasowe, mozna dodać w tabeli zmienna przehcowujaca zczy dokonana zostala zmina ceny, a najlepiej takie puścić crona raz w nocy zmieniajacy cene.
      @event.price_high = @event.price_high * 1.2
      @event.price_low =  @event.price_high
      @event.save()
    end
  end

  def edit
    if current_user.admin? # sprawdzenie czy current user jest adminem
      @event = Event.find(params[:id])
    else
      redirect_to "/events/index"
    end
  end

  def update
    if current_user.admin?
      respond_to do |format|
        event_parmas = params.require(:event).permit(:artist, :placesNumber, :description, :price_low, :price_high, :forAdult, :photo, :event_date, :limitTicket)
        @event = Event.find(params[:id])
        if @event.update(event_parmas)
          format.html { redirect_to @event, notice: 'Event was successfully edited.' }
          format.json { render :show, status: :ok, location: @event }
        else
          format.html { render :edit }
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
      
    else
      redirect_to "/events/index"
    end 
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_allEvents.html.erb
<% @events.each do |event| %>
    <div class="column columnEvent" date="<%= event.event_date %>">
        
            <div  class="media-center">
            <% if event.photo.presence %>
                <%= link_to image_tag(event.photo.url, class: 'media-object'), event.photo.url, target: '_blank' %>
            <% else %>
                <img class="media-object"  src="/system/events/photos/white.png"/>
            <% end %>
            </div>
        
        
        
        <h5><%= link_to event.artist , "/events/#{event.id}" %></h5>
        <p>Price: $<%= event.price_low %> - $<%= event.price_high %></p>
        <p>Remained places: <%= event.placesNumber %></p>
        <p><%= event.description %></p>
        <p>Date: <%= event.event_date %></p>
        
         <%= link_to "Check out", "/events/#{event.id}", class:"btn" %>

        <% if current_user.try(:admin?) %>
            <td><%= link_to 'Edit', edit_event_path(event), class:"btn" %></td>
        <% end %>
    </div>
<% end %>

app/views/events/_eventInfo.html.erb
<div class="text-center">
  <p>
    <h5><%= link_to @event.artist , "/events/#{event.id}", class:"artistInfo" %></h5>
  </p>

  <p>
    <strong>Only:
    <%= @event.placesNumber %>
    Tickets left
    </strong>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>

  <p>
    <strong>Price low:</strong>
    <%= @event.price_low %> $
  </p>

  <p>
    <strong>Price high:</strong>
    <%= @event.price_high %> $
  </p>

  <p>
    <strong>For adult:</strong>
    <%= @event.forAdult %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @event.event_date %>
  </p>

  <p>
    <strong>Maximum tickets per person:</strong>
    <%= @event.limitTicket %>
  </p>

    <% if @event.photo.presence %>
        <div class="media-center">
            <%= link_to image_tag( @event.photo.url, class: 'media-object'),  @event.photo.url, target: '_blank' %>
        </div>
    <%end%>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, :html => {:multipart => true } ) do |form| %>
  &nbsp
  
  <% if event.errors.any? %>
    <div id="error_explanation" class="text-center" style="margin: 0px auto 5px auto;" >
    <h2  class="text-center"><%= pluralize(event.errors.count, "error") %> during sending a request</h2>
    <ul>
      <% event.errors.full_messages.each do |message| %> 
      <li><%= message %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist, id: :event_artist %>
  </div>


  <div class="field">
    <%= form.label :placesNumber %>
    <%= form.number_field :placesNumber,  min: 0, id: :event_placesNumber %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description %>
  </div>

  <div class="field">
    <%= form.label :price_low %>
    <%= form.number_field :price_low, min: 0, id: :event_price_low %>
  </div>

  <div class="field">
    <%= form.label :price_high %>
    <%= form.number_field :price_high, min: 0, id: :event_price_high %>
  </div>

  <div class="field">
    <%= form.label "Only for adult" %>
    <%= form.check_box  :forAdult, id: :event_forAdult %>
  </div>

  <div class="field">
    <%= form.label "Limit tickets to buy" %>
    <%= form.number_field :limitTicket, id: :limitTicket %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= date_field("event", "event_date") %>
  </div> 

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit buttonName, class: "button expanded" %>
  </div>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<div class="text-center twelve columns" style="margin-top:5px;">
    <h1>Editing event</h1>
</div>
<%= render 'form', event: @event, buttonName: "Edit Event" %>


<div class="text-center">
    <%= link_to 'Show', @event, class: "btn", style:"margin-bottom:5px" %>
    <%= link_to 'Back', :back, class: "btn", style:"margin-bottom:5px" %>
</div>

app/views/events/index.html.erb
<div class="text-center twelve columns" style="margin-top:5px;">
      <hr>
      <h2>Our Newest Events</h2>
      <hr>
</div>


<% if signed_in? %>
      <div class="text-center twelve columns" style="margin:0 5px 10px 5px;">
            <%= link_to 'New event', new_event_url , class: "btn" %>
      </div>
<% end %>


<div class="row small-up-2 medium-up-3 large-up-4">
      <%= render 'events/allEvents', events: @events %>
</div>
 
<% if current_user.try(:admin?) %>
      <div class="text-center twelve columns">
            <hr>
            <h2>Archives</h2>
            <hr>
      </div>

      <div class="row small-up-2 medium-up-3 large-up-4">
            <%= render 'events/allEvents', events: @events = @eventsOld%>
      </div>
<% end %>  


<div class="text-center col-md-4 col-md-offset-4 col-8 col-sm-offset-4 col-xs-offset-2" style="margin-top:15px">
      Date from: <input type="date" name='dateFrom' class="inputDate "/>
      Date to: <input type="date" name='dateTo' class="inputDate  "/>
</div>

app/views/events/new.html.erb
<div style="text-center">
    <div class="text-center twelve columns" style="margin-top:5px;">
        <h1>New Event</h1>
        <hr>
    </div>

    <%= render 'form', event: @event, buttonName: "Create Event" %>
    <%= link_to 'Back', events_path, class: "btn" %>

</div>

app/views/events/show.html.erb
<div class="text-center">
  <p id="komunikat"><%= flash[:komunikat] %></p>

  <%if @canBuy==false %>
    Tickets will be released for sale one month before the show
  <%end%>


  <%if @ticket.present? %>
    <%= render "tickets/form", ticket: @ticket, buttonName: "Buy" %>
  <%elsif current_user%>
    <%= render "tickets/form", ticket: Ticket.new( :event_id=>@event.id, :user_id=>current_user.id), buttonName: "Buy", ticketReservedArray: @ticketReservedArray %>
  <%else%>
    <%= render "tickets/form", ticket: Ticket.new(:event_id=>@event.id), buttonName: "Buy", ticketReservedArray: @ticketReservedArray %>
  <%end%>



  <div class="text-center twelve columns" style="margin-top:5px;">
      <hr>
      <h2>Event Information</h2> 
      <hr>
  </div>
  <%= render 'events/eventInfo', event: @event %>
  

  <div class="text-center twelve columns" style="margin-top:5px;">
      <hr>
      <h2>Bought Tickets</h2> 
      <hr>
  </div>

  <%= render "tickets/ticket_list", tickets: tickets = @event.tickets, allTickets: true %>



  <div style="text-center">  
    <%= link_to 'Back', :back, class:"btn btnBack" %>
  </div>
  
</div>