config/routes.rb
Rails.application.routes.draw do


  namespace :users do
    get 'index'  => 'users#index'
  end

  namespace :users do
    get 'money/index'
    post 'money/index' => 'money#update'
    post 'users' => 'registration#create'
    get 'ticket/show'
    get 'ticket/wantdelete/:id' => "ticket#wantdelete", :as => :ticket_wantdelete
    get 'showTickets/:id' => "ticket#showTickets", :as => :ticket_showTickets
    
  end

  get 'events/edit'
  patch 'events/:id' => 'events#update', :as => :events_update

  resources :events, :only => [:index, :new, :create, :show, :edit]

  resources :users, :only => [:index]

  resources :tickets
  
  devise_for :users , :controllers => { registrations: 'users/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  post '/users' => 'users#create'

  


  root :to  => "events#index"
  # root :to  => "tickets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :event
    belongs_to :user
    validates :email_address, :presence => true
    validates :address, :presence => true
    validates :price, :presence => true, numericality: { greater_than: 0 }
    validates :seat_id_seq, :presence => true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tickets
  # GET /tickets.json
  def index

    @tickets = Ticket.all
    @allTickets = true
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
    #czu może edytować bilety 
    if(@ticket.user_id == current_user.id || current_user.try(:admin?) )
      #zarezerwowane bilety 
      @ticketsReserved = Ticket.where(event_id: @ticket.event_id)
      @ticketReservedArray = Array.new
      for x in @ticketsReserved
        @ticketReservedArray.push(x.seat_id_seq)
      end
      @canBuy = true
    else
      redirect_to @ticket, alert: 'It\'s not your Ticket!'
    end
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @myErrors=Array.new
    @ifError = false
    @user = User.find(current_user.id)
    @event = Event.find(ticket_params[:event_id].to_i)
    @ticket = Ticket.new(:user_id => ticket_params[:user_id] , :seat_id_seq => "null" , :address => ticket_params[:address], :price => ticket_params[:price], :email_address => ticket_params[:email_address] , :phone =>  ticket_params[:phone], :event_id => ticket_params[:event_id])

    respond_to do |format|

      validation()

      if @ticket.valid? && @ifError == false

        for seatId in params[:seats] # many tickets
          @ticket = Ticket.new(:user_id => ticket_params[:user_id], :seat_id_seq => "null" , :address => ticket_params[:address], :price => ticket_params[:price], :email_address => ticket_params[:email_address] , :phone =>  ticket_params[:phone], :event_id => ticket_params[:event_id])
          @ticket.seat_id_seq=seatId
          @ticket.save
        end
        
        #odejmij pieniadze
        @user.money = @user.money.to_f - ticket_params[:price].to_f * ticket_params[:numberOfTickets].to_f
        @user.save()

        #odejmij liczbe ogolnych biletów
        reduceNumberOfTickets(@ticket.event_id, ticket_params[:numberOfTickets].to_i)
        
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        #zarezerwowane bilety 
        @ticketsReserved = Ticket.where(event_id: ticket_params[:event_id].to_i)
        @ticketReservedArray = Array.new
        for x in @ticketsReserved
          @ticketReservedArray.push(x.seat_id_seq)
        end

        #sprawdzenie czy juz mozna kupowac (mozna kupwoac 1 miesiac przed eventem)
        @canBuy = false
        if @event.event_date - 1.months < Date.today
          @canBuy = true
        end

        for myError in @myErrors
          @ticket.errors.add( myError[0], myError[1])
        end
        format.html { render 'events/show' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    @myErrors=Array.new
    @ifError = false
    @user = User.find(@ticket.user_id)
    @user.money = @user.money.to_f + @ticket.price.to_f
    @event = Event.find(ticket_params[:event_id].to_i)

    validation()
    
    if ticket_params[:numberOfTickets].to_i>1
      @myErrors.push([" ",'Select only one seat'])
      @ifError = true
    end

    respond_to do |format|
      if @ticket.valid? && @ifError == false
          @user.money = @user.money.to_f - ticket_params[:price].to_f
          @user.save()

          @ticket.update(:user_id => ticket_params[:user_id] , :seat_id_seq => params[:seats][0] , :address => ticket_params[:address], :price => ticket_params[:price], :email_address => ticket_params[:email_address] , :phone =>  ticket_params[:phone], :event_id => ticket_params[:event_id])
          format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
          format.json { render :show, status: :ok, location: @ticket }
      else
        @user.money = @user.money.to_f - @ticket.price.to_f
        @user.save()
        
        @ticketsReserved = Ticket.where(event_id: ticket_params[:event_id].to_i)
        @ticketReservedArray = Array.new
        for x in @ticketsReserved
          @ticketReservedArray.push(x.seat_id_seq)
        end

        #sprawdzenie czy juz mozna kupowac (mozna kupwoac 1 miesiac przed eventem)
        @canBuy = false
        if @event.event_date - 1.months < Date.today
          @canBuy = true
        end

        for myError in @myErrors
          @ticket.errors.add( myError[0], myError[1])
        end
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @user = User.find(@ticket.user_id)
    @user.money+=@ticket.price_return
    

    @event = Event.find(@ticket.event_id)
    @event.placesNumber+=1

    @ticket.destroy
    @user.save
    @event.save
    
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def reduceNumberOfTickets(event_id, number)
      @eventUpdate = Event.find(event_id)
      @eventUpdate.placesNumber -= number
      @eventUpdate.save()
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:user_id, :seat_id_seq, :address, :price, :email_address, :phone, :event_id, :numberOfTickets, :seats)
    end

    def validation
      @ifError = false
        #check money
      if @user.money.to_f - ticket_params[:price].to_f * ticket_params[:numberOfTickets].to_f  < 0
        @myErrors.push([" ",'You don\'t have enough money.'])
        @ifError = true
      end

      #check adult
      if !@user.adult
        if @event.forAdult == true
          @myErrors.push([" ",'You can not take part in this event (underage)'])
          @ifError = true
        end
      end

      #check price, but the price is checked before sending form
      if ticket_params[:price].to_f < @event.price_low || ticket_params[:price].to_f > @event.price_high
        @myErrors.push([:price,'Invalid Price'])
        @ifError = true
      end

      #check bought number of tickets
      if ticket_params[:numberOfTickets].to_i<1
        @myErrors.push([" ",'Choose your seat'])
        @ifError = true
      end


      #check number of tickets 0
      if @event.limitTicket != nil
        if ticket_params[:numberOfTickets].to_i + @user.tickets.where(event_id: ticket_params[:event_id].to_i ).count > @event.limitTicket
          @myErrors.push([" ",'You can\'t buy more then ' + @event.limitTicket.to_s + ' tickets'])
          @ifError = true
        end
      end

      return  @ifError

    end


end

app/controllers/users/ticket_controller.rb
class Users::TicketController < ApplicationController
  before_action :authenticate_user! 
  
  def show
    @tickets = Ticket.where(:user_id => current_user.id )
  end

  def wantdelete
    id_ticket= [params[:id]][0]
    @ticket = Ticket.find(id_ticket)
    @ticket.status = 1
    @ticket.price_return = (@ticket.price * 0.4 + ((@ticket.event.event_date.mjd - Date.today.mjd).to_f()/(@ticket.event.event_date.mjd - Date.today.mjd + 1))*0.5*@ticket.price ).round(2)
    @ticket.save
    redirect_to '/users/ticket/show', notice: 'Zgłoszono wniosek to zwrotu ticketu.'
  end

  def showTickets
    @name = User.find(params[:id])
    @tickets = Ticket.where(:user_id => params[:id])
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/user/ticket_helper.rb
module User::TicketHelper
end

app/helpers/users/ticket_helper.rb
module Users::TicketHelper
end

app/views/tickets/_form.html.erb
<% if ticket.event.placesNumber==0 %>
  <strong class="alert"> Tickets are sold out </strong>
<% end %>

<%= form_with(model: ticket, local: true, id: "buyTicket") do |form| %>
  <%if current_user %>
    <% if ticket.errors.any? %>
      <div id="error_explanation" class="text-center" style="margin: 0px auto 5px auto;">
        <h2  class="text-center"><%= pluralize(ticket.errors.count, "error") %> during sending a request</h2>

        <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <!--<div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id, id: :ticket_user_id %>
    </div>

      <div class="field">
      <%= form.label :event_id %>
      <%= form.text_field :event_id, id: :ticket_event_id %>
    </div> -->

    
    <div class="row">
      <%= form.hidden_field :user_id %>
    </div>

      <div class="row">
      <%= form.hidden_field :event_id %>
    </div>
    
    
    <% if ticket.event_id.present? %>
      <div class="text-center twelve columns" style="margin-top:5px;">
          <h2>Ticket for <%= ticket.event.artist %> event</h2> 
          <hr>
      </div>
    <% end %>

    <% if ticket.seat_id_seq.present? && ticket.seat_id_seq!='null' %>
      <div class="row">
        <%= form.label "Your previous seat" %>
        <%= form.text_area :seat_id_seq, id: :seat_id_seq_id  %>
      </div>
    <% end %>

    <div class="row">
      <%= form.label "Your seats" , class: "col-5" %>
      <div class="col-2"></div>
      <%= form.label :email_address, class: "col-5 "%>
    
    </div>

    <div class="row">
    <%= form.text_field "  ", :readonly => !current_user.try(:admin?), id: :ticket_seat_id_seq, class: " col-5" %>
    <div class="col-2"></div>
      <% if ticket.user_id.present? %>
        <%= form.text_field :email_address, id: :ticket_email_address, :readonly => !current_user.try(:admin?),  value: ticket.user.email, class: " col-5" %>
      <% else %>
        <%= form.text_field :email_address, id: :ticket_email_address, :readonly => !current_user.try(:admin?),  value: current_user.email, class: " col-5" %>
      <% end %>
    </div>


    <div class="row text-center">
      
      <%= form.label :price %> 
      <label>&nbsp</label>
      <label id='priceShow'> <%= ticket.event.price_low %></label> 
      <label>$</label>
      <%= form.range_field :price, id: :ticket_price,:step => '.1', min: ticket.event.price_low, max: ticket.event.price_high, value: ticket.event.price_low, class:"rangeInput col-10"%>
      
    </div>

    <div class="row">
      <%= form.label :address %>
      <%= form.text_area :address, id: :ticket_address  %>
    </div>

    <div class="row">
      <%= form.label :phone %>
      <%= form.text_field :phone, id: :ticket_phone %>
    </div>


    <div class="row">
      <%= form.label "How many tickets?" %>
      <%= form.number_field :numberOfTickets, id: :numberOfTickets, min:1 ,max:ticket.event.limitTicket, value:0, :readonly => true %>
    </div>

  <% end %>

  <% if signed_in? %>
    <h5 class='col-12'> Reserve your places</h5>
  <% else %>
    <h2 class='col-12'> Reserved places</h2>
  <% end %>

  <div class="row text-center divTable">
    <% initial = ticket.event.artist[0] %>
    <% for i in 1..ticket.event.placesNumberAll %>
      <% if @ticketReservedArray.include? initial+i.to_s %>
        <div  title="Reserved" class='col-1 col-xs-1 seat reserved'><%= initial+i.to_s %> </div>
      <% else %>
        <div class='col-1 col-xs-1 seat empty'><%= initial+i.to_s %> </div>
      <% end %>
    <% end %>
  </div>

  <% if signed_in? %>
      <div class="actions">
      <%= form.submit buttonName ,class: "button expanded" , disabled: (!@canBuy || ticket.event.placesNumber==0) && !current_user.try(:admin?) %>
    </div>
  <%end%>
<% end %>

app/views/tickets/_ticketInfo.html.erb
<div class="text-center">
  <p>
    <strong>Owner:</strong>
     <%= link_to @ticket.user.email, "/users/showTickets/#{@ticket.user.id}", style:"text-decoration:underline "%>
  </p>

  <p>
    <strong>Seat id sql:</strong>
    <%= @ticket.seat_id_seq %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @ticket.address %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @ticket.price %> $
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @ticket.phone %>
  </p>

  <% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_ticket_path(@ticket), class:"btn" %>
  <% end %>
</div>

<div class="text-center twelve columns" style="margin-top:5px;">
    <h1>Event's Information</h1>
    <hr>
</div>

app/views/tickets/_ticket_list.html.erb
<% if current_user.try(:admin?) %>

<% end %>  

<table align="center" class="ticketTable">
  <thead>
    <tr>
      <th>Artist name</th>
      <th>Owner</th>
      <th>Seat</th>
      <th>Price</th>
      <th>Address</th>
      <!-- <th>Email address</th> -->
      <th>Phone</th>
      <th>Price to return</th>
      <th colspan="4"></th>
    </tr>
  </thead>


  <tbody>
    <% tickets.each do |ticket| %>
      <tr class=<%= "status" + ticket.status.to_s %> >
        <% if ticket.event.artist.present? %>
          <td style="text-decoration: underline;"><%= link_to ticket.event.artist , "/events/#{ticket.event.id}" %></td>
        <% else %> 
          <td></td>
        <% end %> 
        <td style="text-decoration: underline;"><%= link_to ticket.user.email, "/users/showTickets/#{ticket.user.id}"%></td>

        <td><%= ticket.seat_id_seq %></td>

        <td><%= ticket.price %> $ </td>
        <td><%= ticket.address %></td>
        <!--<td><%= ticket.email_address %></td> %> -->
        <td><%= ticket.phone %></td>
        <% if ticket.price_return.present? %>
          <td><%= ticket.price_return %> $</td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Show', ticket, class: "btn btn-sm" %></td>
        <% if current_user.try(:admin?) || (ticket.user == current_user && ticket.status == 0)%>
          <td><%= link_to 'Edit', edit_ticket_path(ticket), class: "btn btn-sm"  %></td>
        <% else %>
          <td></td>
        <% end %>

        <% if ticket.event.event_date >= Date.today && ticket.status == 0 && allTickets==false %>
          <td><%= link_to 'Return for ' + (ticket.price * 0.4 + ((ticket.event.event_date.mjd - Date.today.mjd).to_f()/(ticket.event.event_date.mjd - Date.today.mjd + 1))*0.5*ticket.price ).round(2).to_s + '$', users_ticket_wantdelete_path(:id => ticket.id), class: "btn" %></td>
        <% else %>
          <td></td>
        <% end %> 
        <% if current_user.try(:admin?) && ticket.status == 1 %>
          <td><%= link_to 'Return Money', ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm" %></td>
        <% else %>
          <td></td>
        <% end %>  
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/edit.html.erb
<h1 class="text-center">Editing Ticket</h1>



<%= render 'form', ticket: @ticket, buttonName: "Edit" %>


<div class="text-center">
<%= link_to 'Show', @ticket, class: "btn", style:"margin-bottom:5px" %>
<%= link_to 'Back', :back, class: "btn", style:"margin-bottom:5px" %>
</div>

app/views/tickets/index.html.erb
<div class="text-center twelve columns" style="margin-top:5px;">
    <h1>Tickets</h1>
    <hr>
</div>

<%= render 'tickets/ticket_list', tickets:@tickets, allTickets: true %>
<br>

<!-- <%= link_to 'New Ticket', new_ticket_path %> -->

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket, buttonName: "Buy" %>
<div class="row large-up-12">
    <%= render 'events/allEvents', events: @events = Event.all %>
</div>

<%= link_to 'Back', :back %>

app/views/tickets/show.html.erb
<div class="text-center twelve columns" style="margin-top:5px;">
    <h1>Ticket's Information</h1>
    <hr>
</div>

<%= render 'tickets/ticketInfo', ticket: @ticket %>

<%= render 'events/eventInfo', event: @event = @ticket.event %>

<div class="text-center">
  <%= link_to 'Back', :back, class: "btn", style: "margin-bottom:10px" %>
</div>