config/routes.rb
Rails.application.routes.draw do


  namespace :users do
    get 'index'  => 'users#index'
  end

  namespace :users do
    get 'money/index'
    post 'money/index' => 'money#update'
    post 'users' => 'registration#create'
    get 'ticket/show'
    get 'ticket/wantdelete/:id' => "ticket#wantdelete", :as => :ticket_wantdelete
    get 'showTickets/:id' => "ticket#showTickets", :as => :ticket_showTickets
    
  end

  get 'events/edit'
  patch 'events/:id' => 'events#update', :as => :events_update

  resources :events, :only => [:index, :new, :create, :show, :edit]

  resources :users, :only => [:index]

  resources :tickets
  
  devise_for :users , :controllers => { registrations: 'users/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  post '/users' => 'users#create'

  


  root :to  => "events#index"
  # root :to  => "tickets#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<div class="callout secondary" style="margin-top:10px;">
    <div class="row">
        <div class="medium-2 large-2 columns">
            <h5 class="text-center" style="margin-top:5px ">Event4U</h5>
        </div>
        <div class="medium-6 large-6  columns">
            <ul class="menu">
                <%if signed_in? %>
                    <li><%= link_to "My tickets", users_ticket_show_path %></li>
                    <li><%= link_to "Add money", users_money_index_path %></li>
                <% end %>
                <%if current_user.try(:admin?) %>
                    <li><%= link_to "Tickets", tickets_url %></li>
                    <li><%= link_to "Users", users_index_path %></li>
                <% end %>
            </ul>
        </div>
        <div class="medium-3 large-4 columns">
            <ul class="menu">
                <%if signed_in?%>
                    <li><%=link_to current_user.email, edit_user_registration_path%></li>
                    <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
                <%else%>
                    <li><%=link_to "Register", new_user_registration_path%></li>
                    <li><%=link_to "Login", new_user_session_path%></li>
                <%end%>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
 <!-- Start Top Bar -->
    <div class="top-bar" style="height:auto">
      <div class="top-bar-left">
        <ul class="menu">
          <li><%= link_to "Event4U", root_path %> </li>
          <%if signed_in? %>
            <li><%= link_to "My tickets", users_ticket_show_path %></li>
            <li><%= link_to "Add money", users_money_index_path %></li>
          <% end %>
           <%if current_user.try(:admin?) %>
            <li><%= link_to "Tickets", tickets_url %></li>
            <li><%= link_to "Users", users_index_path %></li>
          <% end %>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <%if signed_in? %>
            <li><%=link_to current_user.email, edit_user_registration_path %></li>
            <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
          <%else%>
            <li><%=link_to "Register", new_user_registration_path%></li>
            <li><%=link_to "Login", new_user_session_path%></li>
          <%end%>
        </ul>
      </div>
    </div>

<% if notice %>
  <p class="alert alert-success text-center bold"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger text-center bold"><%= alert %></p>
<% end %>

app/views/layouts/_mainContent.html.erb
    <div id="main-content" class="full-min-height container">
      <%= yield %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Events</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>


  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= render 'layouts/mainContent' %>

    <%= render 'layouts/footer' %>

  </body>

</html>